export interface Legend {
  id: string;
  rank: number;
  name: string;
  alternate?: string;
  era: string;
  description: string;
  significance: string;
  quote?: {
    text: string;
    source: string;
  };
}

export const legends: Legend[] = [
  {
    id: "jesus-christ",
    rank: 1,
    name: "Jesus Christ",
    era: "1 CE",
    description: "Founder of Christianity, whose teachings shaped Western civilization and moral philosophy.",
    significance: "Spiritual and moral foundation for billions; transformed human understanding of compassion and redemption.",
    quote: {
      text: "Love your enemies, do good to those who hate you.",
      source: "Luke 6:27",
    },
  },
  {
    id: "muhammad",
    rank: 2,
    name: "Muhammad ibn Abdullah",
    era: "570–632 CE",
    description: "Prophet and founder of Islam, uniting Arabia and establishing a major world religion.",
    significance: "Created Islam, a faith of nearly 2 billion adherents; codified law, trade, and governance across continents.",
    quote: {
      text: "Seek knowledge from the cradle to the grave.",
      source: "Hadith",
    },
  },
  {
    id: "buddha",
    rank: 3,
    name: "Siddhartha Gautama (The Buddha)",
    era: "563–483 BCE",
    description: "Founder of Buddhism, pioneering meditation and the path to enlightenment.",
    significance: "Established Buddhism affecting 500+ million people; introduced non-theistic spirituality and inner discipline.",
    quote: {
      text: "Do not believe anything simply because you have heard it.",
      source: "Kalama Sutta",
    },
  },
  {
    id: "shakespeare",
    rank: 4,
    name: "William Shakespeare",
    era: "1564–1616",
    description: "English dramatist and poet who defined modern literature and human psychology.",
    significance: "Created works exploring love, ambition, and moral conflict; shaped the English language itself.",
    quote: {
      text: "To be, or not to be, that is the question.",
      source: "Hamlet",
    },
  },
  {
    id: "socrates",
    rank: 5,
    name: "Socrates of Athens",
    era: "470–399 BCE",
    description: "Athenian philosopher who pioneered critical inquiry and the examined life.",
    significance: "Founded Western philosophy's method of questioning; influenced Plato, Aristotle, and all Western thought.",
    quote: {
      text: "The unexamined life is not worth living.",
      source: "Apology",
    },
  },
  {
    id: "napoleon",
    rank: 6,
    name: "Napoléon Bonaparte",
    era: "1769–1821",
    description: "French military commander and emperor who reshaped European law and politics.",
    significance: "Spread Enlightenment ideals through the Napoleonic Code; redrew European borders and modernized warfare.",
    quote: {
      text: "History is a set of lies agreed upon.",
      source: "Attributed",
    },
  },
  {
    id: "newton",
    rank: 7,
    name: "Sir Isaac Newton",
    era: "1642–1726",
    description: "English mathematician and physicist who founded classical mechanics and calculus.",
    significance: "Established the laws of motion and universal gravitation; launched the scientific revolution.",
    quote: {
      text: "If I have seen further, it is by standing on the shoulders of giants.",
      source: "Letter to Robert Hooke",
    },
  },
  {
    id: "leonardo",
    rank: 8,
    name: "Leonardo da Vinci",
    era: "1452–1519",
    description: "Italian Renaissance master of art, science, and engineering.",
    significance: "Embodied human curiosity across disciplines; pioneered observational science and anatomical study.",
    quote: {
      text: "Learning never exhausts the mind.",
      source: "Notebooks",
    },
  },
  {
    id: "plato",
    rank: 9,
    name: "Plato of Athens",
    era: "428–348 BCE",
    description: "Greek philosopher who founded the Academy and developed theory of Forms.",
    significance: "Created systematic philosophy; his idealism shaped metaphysics, ethics, and politics for millennia.",
    quote: {
      text: "The beginning is the most important part of the work.",
      source: "Republic",
    },
  },
  {
    id: "einstein",
    rank: 10,
    name: "Albert Einstein",
    era: "1879–1955",
    description: "German-Swiss physicist who revolutionized understanding of space, time, and energy.",
    significance: "Discovered relativity and equivalence of mass and energy; became symbol of scientific genius.",
    quote: {
      text: "Imagination is more important than knowledge.",
      source: "Saturday Evening Post, 1929",
    },
  },
  {
    id: "aristotle",
    rank: 11,
    name: "Aristotle of Stagira",
    era: "384–322 BCE",
    description: "Greek philosopher who systematized knowledge across logic, ethics, physics, and politics.",
    significance: "Founded formal logic; influenced Islamic, Jewish, and Christian philosophy for two millennia.",
    quote: {
      text: "Excellence is not an act, but a habit.",
      source: "Nicomachean Ethics",
    },
  },
  {
    id: "curie",
    rank: 12,
    name: "Marie Skłodowska Curie",
    era: "1867–1934",
    description: "Polish-French physicist who discovered radioactivity and pioneered nuclear science.",
    significance: "First woman to win Nobel Prize; only person to win Nobel in two scientific fields.",
    quote: {
      text: "Nothing in life is to be feared, it is only to be understood.",
      source: "Attributed",
    },
  },
  {
    id: "marx",
    rank: 13,
    name: "Karl Heinrich Marx",
    era: "1818–1883",
    description: "German philosopher who analyzed capitalism and developed dialectical materialism.",
    significance: "Shaped communist and socialist movements affecting billions; transformed political philosophy.",
    quote: {
      text: "The philosophers have only interpreted the world in various ways; the point is to change it.",
      source: "Theses on Feuerbach",
    },
  },
  {
    id: "darwin-priestley",
    rank: 14,
    name: "Charles Robert Darwin / Joseph Priestley",
    era: "Darwin: 1809–1882 | Priestley: 1733–1804",
    description: "Darwin: founder of evolutionary biology. Priestley: chemist who discovered oxygen.",
    significance: "Darwin: explained origin of species; Priestley: advanced chemistry and rational inquiry.",
    quote: {
      text: "There is grandeur in this view of life.",
      source: "Darwin, On the Origin of Species",
    },
  },
  {
    id: "confucius",
    rank: 15,
    name: "Kong Qiu (Confucius)",
    era: "551–479 BCE",
    description: "Chinese philosopher whose ethics founded Confucianism, shaping East Asian civilization.",
    significance: "Defined virtue, filial piety, and governance; influenced hundreds of millions for 2,500 years.",
    quote: {
      text: "The strength of a nation derives from the integrity of the home.",
      source: "Attributed",
    },
  },
  {
    id: "genghis-khan",
    rank: 16,
    name: "Genghis Khan (Temüjin)",
    era: "1162–1227",
    description: "Mongol emperor who conquered the largest contiguous land empire in history.",
    significance: "United Central Asia; enabled Silk Road trade connecting civilizations across continents.",
    quote: {
      text: "I am the punishment of God. If you had not committed great sins, God would not have sent a punishment like me upon you.",
      source: "Attributed",
    },
  },
  {
    id: "turing",
    rank: 17,
    name: "Alan Mathison Turing",
    era: "1912–1954",
    description: "British mathematician who founded computer science and artificial intelligence.",
    significance: "Invented the Turing machine; cracked Enigma code; pioneered concepts of computation and AI.",
    quote: {
      text: "The question 'Can machines think?' I believe is too meaningless to deserve discussion.",
      source: "Computing Machinery and Intelligence",
    },
  },
  {
    id: "alexander",
    rank: 18,
    name: "Alexander III of Macedon (Alexander the Great)",
    era: "356–323 BCE",
    description: "Macedonian king who built an empire spanning from Greece to India.",
    significance: "Spread Hellenistic culture across the known world; redefined military strategy and political conquest.",
    quote: {
      text: "I am not afraid of an army of lions led by a sheep; I am afraid of an army of sheep led by a lion.",
      source: "Attributed",
    },
  },
  {
    id: "columbus",
    rank: 19,
    name: "Cristoforo Colombo (Christopher Columbus)",
    era: "1451–1506",
    description: "Genoese explorer whose voyage to the Americas initiated global European expansion.",
    significance: "Connected continents and initiated the Age of Exploration, reshaping human history.",
    quote: {
      text: "By prevailing over all obstacles and distractions, one may unfailingly arrive at his chosen goal or destination.",
      source: "Attributed",
    },
  },
  {
    id: "cleopatra",
    rank: 20,
    name: "Cleopatra VII Philopator",
    era: "69–30 BCE",
    description: "Egyptian pharaoh and intellectual who allied with Rome to preserve Egypt's power.",
    significance: "Last active ruler of Ptolemaic Egypt; symbol of political intelligence and diplomatic statecraft.",
    quote: {
      text: "I will not be triumphed over.",
      source: "Attributed",
    },
  },
  {
    id: "caesar",
    rank: 21,
    name: "Gaius Julius Caesar",
    era: "100–44 BCE",
    description: "Roman general and statesman who expanded the empire and transformed Roman politics.",
    significance: "Conquered Gaul; fundamentally altered Roman government and established authoritarian rule.",
    quote: {
      text: "The die is cast.",
      source: "Attributed at the Rubicon",
    },
  },
  {
    id: "galileo",
    rank: 22,
    name: "Galileo Galilei",
    era: "1564–1642",
    description: "Italian astronomer and physicist who advanced observational science and heliocentrism.",
    significance: "Used telescope to study heavens; championed the scientific method against dogma.",
    quote: {
      text: "In questions of science, the authority of a thousand is not worth the humble reasoning of a single individual.",
      source: "Attributed",
    },
  },
  {
    id: "marco-polo",
    rank: 23,
    name: "Marco Polo",
    era: "1254–1324",
    description: "Venetian merchant-explorer who traveled the Silk Road and documented Asia.",
    significance: "Bridged East and West through trade and documentation; pioneered global commerce.",
    quote: {
      text: "I have not told half of what I saw.",
      source: "Attributed on his deathbed",
    },
  },
  {
    id: "marcus-aurelius",
    rank: 24,
    name: "Marcus Aurelius Antoninus Augustus",
    era: "121–180",
    description: "Roman emperor and Stoic philosopher who wrote influential meditations.",
    significance: "Ruled during Pax Romana; his philosophy of virtue shaped Western moral thought.",
    quote: {
      text: "You have power over your mind—not outside events. Realize this, and you will find strength.",
      source: "Meditations",
    },
  },
  {
    id: "copernicus",
    rank: 25,
    name: "Nicolaus Copernicus",
    era: "1473–1543",
    description: "Polish astronomer who proposed the heliocentric model of the solar system.",
    significance: "Revolutionized astronomy; placed Sun at center, enabling modern physics.",
    quote: {
      text: "Mathematics is written for mathematicians.",
      source: "Preface to De revolutionibus",
    },
  },
  {
    id: "joan-of-arc",
    rank: 26,
    name: "Jeanne d'Arc (Joan of Arc)",
    era: "1412–1431",
    description: "French military leader whose victories turned the Hundred Years' War.",
    significance: "Inspired French nationalism; became symbol of courage and conviction.",
    quote: {
      text: "Act, and God will act.",
      source: "Attributed",
    },
  },
  {
    id: "bach",
    rank: 27,
    name: "Johann Sebastian Bach",
    era: "1685–1750",
    description: "German composer who mastered counterpoint and founded modern music theory.",
    significance: "Synthesized Baroque music; influenced all subsequent Western composition.",
    quote: {
      text: "The aim and final reason of all music is nothing else but the glory of God.",
      source: "Attributed",
    },
  },
  {
    id: "hobbes",
    rank: 28,
    name: "Thomas Hobbes",
    era: "1588–1679",
    description: "English philosopher who pioneered social contract theory and modern political science.",
    significance: "Established foundations of political philosophy; shaped theories of state and power.",
    quote: {
      text: "Knowledge is power.",
      source: "Leviathan",
    },
  },
  {
    id: "mozart",
    rank: 29,
    name: "Wolfgang Amadeus Mozart",
    era: "1756–1791",
    description: "Austrian composer who revolutionized classical music with unprecedented genius.",
    significance: "Created 600+ works at high artistic level; defined Classical period.",
    quote: {
      text: "It is a great consolation for me to reflect that the share which the Almighty has been pleased to allow me to take of his great work is a source of such unqualified pleasure.",
      source: "Letters",
    },
  },
  {
    id: "michelangelo",
    rank: 30,
    name: "Michelangelo di Lodovico Buonarroti Simoni",
    era: "1475–1564",
    description: "Italian Renaissance master of sculpture, painting, and architecture.",
    significance: "Created works of unmatched artistic power; shaped Renaissance ideals.",
    quote: {
      text: "The true work of art is but a shadow of the divine perfection.",
      source: "Attributed",
    },
  },
  {
    id: "leibniz",
    rank: 31,
    name: "Gottfried Wilhelm Leibniz",
    era: "1646–1716",
    description: "German polymath who invented calculus and advanced philosophy and logic.",
    significance: "Co-founder of calculus; pioneered principles of identity and sufficient reason.",
    quote: {
      text: "There are no two individuals alike in the universe.",
      source: "Monadology",
    },
  },
  {
    id: "archimedes",
    rank: 32,
    name: "Archimedes of Syracuse",
    era: "287–212 BCE",
    description: "Greek mathematician and physicist who advanced geometry and mechanics.",
    significance: "Pioneered mathematical proof; created mechanical inventions; founded hydrostatics.",
    quote: {
      text: "Give me a lever long enough and a fulcrum on which to place it, and I shall move the world.",
      source: "Attributed",
    },
  },
  {
    id: "jobs",
    rank: 33,
    name: "Steven Paul Jobs",
    era: "1955–2011",
    description: "American entrepreneur who revolutionized personal computing and digital design.",
    significance: "Founded Apple; shaped modern technology, design, and consumer electronics.",
    quote: {
      text: "The only way to do great work is to love what you do.",
      source: "Stanford Commencement",
    },
  },
  {
    id: "kant",
    rank: 34,
    name: "Immanuel Kant",
    era: "1724–1804",
    description: "German philosopher who synthesized rationalism and empiricism into critical philosophy.",
    significance: "Revolutionized epistemology; established foundations of modern philosophy.",
    quote: {
      text: "Sapere aude! Dare to know!",
      source: "An Answer to the Question: What is Enlightenment?",
    },
  },
  {
    id: "locke",
    rank: 35,
    name: "John Locke",
    era: "1632–1704",
    description: "English philosopher who founded empiricism and theory of natural rights.",
    significance: "Established foundations of liberalism; influenced American and French revolutions.",
    quote: {
      text: "All mankind... being all equal and independent, no one ought to harm another in his life, health, liberty, or possessions.",
      source: "Second Treatise of Government",
    },
  },
  {
    id: "beethoven",
    rank: 36,
    name: "Ludwig van Beethoven",
    era: "1770–1827",
    description: "German composer who revolutionized music from Classical to Romantic era.",
    significance: "Transformed symphony and sonata; achieved artistic mastery while deaf.",
    quote: {
      text: "Music is the electrical soil in which the spirit lives, thinks and invents.",
      source: "Attributed",
    },
  },
  {
    id: "euclid",
    rank: 37,
    name: "Euclid of Alexandria",
    era: "300 BCE",
    description: "Greek mathematician who systematized geometry and established axiomatic method.",
    significance: "Created foundational Elements; established geometric method used for 2,000 years.",
    quote: {
      text: "There is no royal road to geometry.",
      source: "Attributed",
    },
  },
  {
    id: "aquinas-luther",
    rank: 38,
    name: "Thomas Aquinas / Martin Luther",
    era: "Aquinas: 1225–1274 | Luther: 1483–1546",
    description: "Aquinas: synthesized Aristotle with theology. Luther: initiated Protestant Reformation.",
    significance: "Aquinas: shaped Catholic thought; Luther: fractured Western Christianity.",
    quote: {
      text: "Grace perfects nature.",
      source: "Aquinas, Summa Theologiae",
    },
  },
  {
    id: "homer",
    rank: 39,
    name: "Homer",
    era: "800 BCE",
    description: "Greek poet whose epics established Western literature and mythology.",
    significance: "Iliad and Odyssey shaped Greek culture and influenced all Western literature.",
    quote: {
      text: "Of all creatures that breathe and move upon the earth, nothing is more miserable than man.",
      source: "Iliad",
    },
  },
  {
    id: "mill-rousseau",
    rank: 40,
    name: "John Stuart Mill / Jean-Jacques Rousseau",
    era: "Mill: 1806–1873 | Rousseau: 1712–1778",
    description: "Mill: pioneered utilitarianism and liberty. Rousseau: developed social contract theory.",
    significance: "Mill: influenced ethics and political theory; Rousseau: inspired democratic revolutions.",
    quote: {
      text: "He who would live must bow to the law of his nature.",
      source: "Rousseau",
    },
  },
  {
    id: "bentham",
    rank: 41,
    name: "Jeremy Bentham",
    era: "1748–1832",
    description: "English philosopher who founded utilitarianism and reformist political theory.",
    significance: "Established principle of utility as guide to ethics and legislation.",
    quote: {
      text: "It is the greatest happiness of the greatest number that is the measure of right and wrong.",
      source: "Introduction to the Principles",
    },
  },
  {
    id: "dostoevsky",
    rank: 42,
    name: "Fyodor Mikhailovich Dostoevsky",
    era: "1821–1881",
    description: "Russian novelist who explored psychology, suffering, and spiritual redemption.",
    significance: "Created psychological depth in literature; influenced existential and religious philosophy.",
    quote: {
      text: "The soul is healed by loving.",
      source: "Attributed",
    },
  },
  {
    id: "goethe",
    rank: 43,
    name: "Johann Wolfgang von Goethe",
    era: "1749–1832",
    description: "German polymath poet, playwright, and scientist who bridged arts and sciences.",
    significance: "Defined Romantic literature; advanced scientific method in morphology.",
    quote: {
      text: "Everything is only for a moment, anyway.",
      source: "Attributed",
    },
  },
  {
    id: "hume",
    rank: 44,
    name: "David Hume",
    era: "1711–1776",
    description: "Scottish philosopher who advanced empiricism and challenged causality.",
    significance: "Questioned metaphysics; influenced Kant and modern philosophy.",
    quote: {
      text: "A man is nothing but a bundle or collection of different perceptions.",
      source: "Treatise of Human Nature",
    },
  },
  {
    id: "kierkegaard",
    rank: 45,
    name: "Søren Aabye Kierkegaard",
    era: "1813–1855",
    description: "Danish philosopher who founded existentialism and subjective philosophy.",
    significance: "Established existential thought; influenced 20th-century philosophy and theology.",
    quote: {
      text: "Life can only be understood backwards; but it must be lived forwards.",
      source: "Life's Way",
    },
  },
  {
    id: "schiller",
    rank: 46,
    name: "Johann Christoph Friedrich von Schiller",
    era: "1759–1805",
    description: "German poet and playwright who explored freedom and human nature.",
    significance: "Master of dramatic and lyrical poetry; influenced German and world literature.",
    quote: {
      text: "Freedom is only in the land of dreams.",
      source: "Attributed",
    },
  },
  {
    id: "pythagoras",
    rank: 47,
    name: "Pythagoras of Samos",
    era: "570–495 BCE",
    description: "Greek mathematician and philosopher who founded mathematical and mystical schools.",
    significance: "Discovered mathematical relationships; pioneered abstract reasoning in mathematics.",
    quote: {
      text: "All things are numbers.",
      source: "Attributed",
    },
  },
  {
    id: "russell",
    rank: 48,
    name: "Bertrand Arthur William Russell",
    era: "1872–1970",
    description: "British philosopher who advanced mathematical logic and philosophy of language.",
    significance: "Pioneer of analytic philosophy; challenged dogma throughout life.",
    quote: {
      text: "What is wanted is not the will to believe, but the wish to find out.",
      source: "Free Man's Worship",
    },
  },
  {
    id: "wittgenstein",
    rank: 49,
    name: "Ludwig Josef Johann Wittgenstein",
    era: "1889–1951",
    description: "Austrian philosopher who revolutionized philosophy of language and logic.",
    significance: "Redefined philosophical problems through language analysis.",
    quote: {
      text: "The limits of my language mean the limits of my world.",
      source: "Tractatus Logico-Philosophicus",
    },
  },
  {
    id: "hypatia-et-al",
    rank: 50,
    name: "Hypatia of Alexandria et al.",
    era: "Hypatia: 350–415 | Van Gogh: 1853–1890 | Others: Various",
    description: "Hypatia: mathematician and astronomer. Van Gogh: revolutionary painter. Vivaldi: master composer. Nietzsche, Schopenhauer, Jung, Freud: transformative thinkers.",
    significance: "Each reshaped their field: mathematics, visual art, music, and psychology.",
    quote: {
      text: "Fables should be taught as fables, myths as myths, and miracles as poetic fantasies.",
      source: "Hypatia, attributed",
    },
  },
];
