export type MathSymbol = {
  glyph: string;
  name: string;
  tex?: string[];
  group:
    | "greek-lower"
    | "greek-upper"
    | "operator"
    | "relation"
    | "set-logic"
    | "calculus"
    | "quantum-notation"
    | "constant"
    | "other";
  meanings: string[];
  example?: string;
};

const lower: [string, string, string[], string?][] = [
  [
    "α",
    "alpha",
    ["A parameter, angle, fine-structure constant, or quantum amplitude."],
    "α|0⟩ + β|1⟩",
  ],
  [
    "β",
    "beta",
    ["A parameter, regression coefficient, beta particle, or quantum amplitude."],
    "α|0⟩ + β|1⟩",
  ],
  [
    "γ",
    "gamma",
    ["The Lorentz factor, a gamma ray, or the Euler–Mascheroni constant."],
    "γ = 1 / √(1 − v²/c²)",
  ],
  ["δ", "delta", ["A small change, variation, or Dirac delta distribution."], "δx"],
  ["ε", "epsilon", ["A small quantity, permittivity, or error tolerance."], "ε₀"],
  ["ζ", "zeta", ["The Riemann zeta function or a damping ratio."], "ζ(s)"],
  [
    "η",
    "eta",
    ["Efficiency, viscosity, or a learning rate."],
    "η = useful output / input",
  ],
  ["θ", "theta", ["An angle, polar coordinate, or unknown model parameter."], "sin θ"],
  ["ι", "iota", ["A small index or the inclusion map in mathematics."], "ι: A ↪ B"],
  ["κ", "kappa", ["Curvature, thermal conductivity, or a condition number."], "κ"],
  [
    "λ",
    "lambda",
    ["Wavelength, an eigenvalue, decay rate, or lambda-calculus function."],
    "λ = h/p",
  ],
  [
    "μ",
    "mu (mew)",
    ["The SI prefix micro (10⁻⁶), mean, friction coefficient, or reduced mass."],
    "μm = 10⁻⁶ m",
  ],
  [
    "ν",
    "nu (new)",
    ["Frequency in physics; also used for neutrino flavours or degrees of freedom."],
    "E = hν",
  ],
  [
    "ξ",
    "xi (ksee)",
    ["A random variable, correlation length, or spatial coordinate."],
    "ξ",
  ],
  [
    "ο",
    "omicron",
    ["An ordinary Greek letter that is rarely used as a mathematical symbol."],
    "ο",
  ],
  [
    "π",
    "pi",
    ["The circle constant (about 3.14159…) or a product symbol when capitalised as Π."],
    "C = 2πr",
  ],
  [
    "ρ",
    "rho (row)",
    ["Mass or charge density, correlation, or a quantum density matrix."],
    "ρ = m/V",
  ],
  [
    "σ",
    "sigma",
    [
      "Standard deviation, cross-section, mechanical stress, or the Stefan–Boltzmann constant.",
    ],
    "σ = √variance",
  ],
  ["τ", "tau", ["A time constant, torque, proper time, or 2π."], "τ = 2π"],
  [
    "υ",
    "upsilon",
    ["A Greek letter used in particle names; rarely a standalone variable."],
    "υ",
  ],
  ["φ", "phi (fye)", ["An angle, scalar field, potential, or phase."], "φ(x)"],
  ["χ", "chi (kye)", ["A chi-squared statistic, susceptibility, or character."], "χ²"],
  ["ψ", "psi (sigh)", ["A quantum wave function or state vector."], "|ψ⟩"],
  [
    "ω",
    "omega",
    ["Angular frequency; capital Ω also denotes ohms or solid angle."],
    "ω = 2πf",
  ],
];

const upper: [string, string, string[], string?][] = [
  [
    "Α",
    "Alpha",
    ["Uppercase Greek alpha; it looks like Latin A and is rarely used as a symbol."],
    "Α",
  ],
  [
    "Β",
    "Beta",
    ["Uppercase Greek beta; it looks like Latin B and is rarely used as a symbol."],
    "Β",
  ],
  ["Γ", "Gamma", ["The gamma function or a matrix of Dirac gamma matrices."], "Γ(n)"],
  [
    "Δ",
    "Delta",
    ["A finite change or difference; ∇² is the Laplacian, sometimes written Δ."],
    "Δx = x₂ − x₁",
  ],
  [
    "Ε",
    "Epsilon",
    ["Uppercase Greek epsilon; it looks like Latin E and is rarely used as a symbol."],
    "Ε",
  ],
  [
    "Ζ",
    "Zeta",
    ["Uppercase Greek zeta; it looks like Latin Z and is rarely used as a symbol."],
    "Ζ",
  ],
  [
    "Η",
    "Eta",
    ["Uppercase Greek eta; it looks like Latin H and is rarely used as a symbol."],
    "Η",
  ],
  [
    "Θ",
    "Theta",
    ["An angle or the asymptotic order notation Θ(n log n)."],
    "T(n) = Θ(n log n)",
  ],
  [
    "Ι",
    "Iota",
    ["Uppercase Greek iota; it looks like Latin I and is rarely used as a symbol."],
    "Ι",
  ],
  [
    "Κ",
    "Kappa",
    ["Uppercase Greek kappa; it looks like Latin K and is rarely used as a symbol."],
    "Κ",
  ],
  [
    "Λ",
    "Lambda",
    ["An eigenvalue, cosmological constant, or lambda-particle symbol."],
    "Av = λv",
  ],
  [
    "Μ",
    "Mu",
    ["Uppercase Greek mu; it looks like Latin M and is rarely used as a symbol."],
    "Μ",
  ],
  [
    "Ν",
    "Nu",
    ["Uppercase Greek nu; it looks like Latin N and is rarely used as a symbol."],
    "Ν",
  ],
  [
    "Ξ",
    "Xi",
    ["A Greek letter used for random variables, coordinates, and particle names."],
    "Ξ",
  ],
  [
    "Ο",
    "Omicron",
    ["Uppercase Greek omicron; it looks like Latin O and is rarely used as a symbol."],
    "Ο",
  ],
  ["Π", "Pi", ["Product notation, analogous to Σ for sums."], "∏ᵢ₌₁ⁿ xᵢ"],
  [
    "Ρ",
    "Rho",
    ["Uppercase Greek rho; it looks like Latin P and is rarely used as a symbol."],
    "Ρ",
  ],
  [
    "Σ",
    "Sigma",
    ["Summation; the lowercase σ has several meanings including standard deviation."],
    "Σᵢ₌₁ⁿ xᵢ",
  ],
  [
    "Τ",
    "Tau",
    ["Uppercase Greek tau; it looks like Latin T and is rarely used as a symbol."],
    "Τ",
  ],
  ["Υ", "Upsilon", ["A Greek letter used in the name of the upsilon meson."], "Υ"],
  ["Φ", "Phi", ["Magnetic flux, a scalar field, or a quantum state label."], "|Φ⁺⟩"],
  [
    "Χ",
    "Chi",
    ["Uppercase Greek chi; it looks like Latin X and is rarely used as a symbol."],
    "Χ",
  ],
  ["Ψ", "Psi", ["A quantum state or wave function symbol."], "Ψ"],
  [
    "Ω",
    "Omega",
    ["Electrical resistance in ohms or solid angle; also a sample space."],
    "R = 4 Ω",
  ],
];

const upperTex: Record<string, string> = {
  Gamma: "\\Gamma",
  Delta: "\\Delta",
  Theta: "\\Theta",
  Lambda: "\\Lambda",
  Xi: "\\Xi",
  Pi: "\\Pi",
  Sigma: "\\Sigma",
  Upsilon: "\\Upsilon",
  Phi: "\\Phi",
  Psi: "\\Psi",
  Omega: "\\Omega",
};

const entry = (
  glyph: string,
  name: string,
  group: MathSymbol["group"],
  meanings: string[],
  tex?: string[],
  example?: string,
): MathSymbol => ({
  glyph,
  name,
  group,
  meanings,
  ...(tex ? { tex } : {}),
  ...(example ? { example } : {}),
});

export const symbols: MathSymbol[] = [
  ...lower.map(([glyph, name, meanings, example]) =>
    entry(
      glyph,
      name,
      "greek-lower",
      meanings,
      [`\\${name.split(" ")[0].toLowerCase()}`],
      example,
    ),
  ),
  ...upper.map(([glyph, name, meanings, example]) =>
    entry(
      glyph,
      name,
      "greek-upper",
      meanings,
      upperTex[name] ? [upperTex[name]] : undefined,
      example,
    ),
  ),
  entry(
    "+",
    "plus",
    "operator",
    ["Addition; combine quantities."],
    undefined,
    "2 + 3 = 5",
  ),
  entry(
    "−",
    "minus",
    "operator",
    ["Subtraction or the negative sign; distinct from a hyphen."],
    undefined,
    "5 − 2 = 3",
  ),
  entry(
    "×",
    "times",
    "operator",
    ["Multiplication, especially between numbers."],
    ["\\times"],
    "3 × 4",
  ),
  entry(
    "·",
    "dot",
    "operator",
    ["Multiplication or a scalar (dot) product."],
    ["\\cdot"],
    "a · b",
  ),
  entry("÷", "divided by", "operator", ["Division."], ["\\div"], "12 ÷ 3"),
  entry(
    "±",
    "plus or minus",
    "operator",
    ["Two possibilities: the positive and negative value."],
    ["\\pm"],
    "x = 3 ± 1",
  ),
  entry(
    "∓",
    "minus or plus",
    "operator",
    ["The paired opposite of ±, used in matching signs."],
    ["\\mp"],
    "a ± b, c ∓ d",
  ),
  entry(
    "=",
    "equals",
    "relation",
    ["The expressions on both sides have the same value."],
    ["\\equals"],
    "2 + 2 = 4",
  ),
  entry(
    "≠",
    "not equal",
    "relation",
    ["The two values are different."],
    ["\\ne"],
    "π ≠ 3",
  ),
  entry(
    "≈",
    "approximately equal",
    "relation",
    ["The values are close, within an understood precision."],
    ["\\approx"],
    "π ≈ 3.14159",
  ),
  entry(
    "≡",
    "identically equal / congruent",
    "relation",
    ["An identity, or congruence modulo an integer."],
    ["\\equiv"],
    "x² − 1 ≡ (x − 1)(x + 1)",
  ),
  entry(
    "∝",
    "proportional to",
    "relation",
    ["One quantity is a constant multiple of another."],
    ["\\propto"],
    "F ∝ 1/r²",
  ),
  entry(
    "<",
    "less than",
    "relation",
    ["The left value is smaller than the right value."],
    ["\\lt"],
    "2 < 5",
  ),
  entry(
    ">",
    "greater than",
    "relation",
    ["The left value is larger than the right value."],
    ["\\gt"],
    "5 > 2",
  ),
  entry(
    "≤",
    "less than or equal",
    "relation",
    ["The left value is smaller than or equal to the right."],
    ["\\le"],
    "x ≤ 10",
  ),
  entry(
    "≥",
    "greater than or equal",
    "relation",
    ["The left value is larger than or equal to the right."],
    ["\\ge"],
    "x ≥ 0",
  ),
  entry(
    "≪",
    "much less than",
    "relation",
    ["The left scale is negligible compared with the right."],
    ["\\ll"],
    "m ≪ M",
  ),
  entry(
    "≫",
    "much greater than",
    "relation",
    ["The left scale is far larger than the right."],
    ["\\gg"],
    "M ≫ m",
  ),
  entry(
    "√",
    "square root",
    "operator",
    ["The non-negative number whose square equals the input."],
    ["\\sqrt"],
    "√9 = 3",
  ),
  entry(
    "∞",
    "infinity",
    "constant",
    ["A concept of unbounded size, not an ordinary real number."],
    ["\\infty"],
    "limₙ→∞",
  ),
  entry(
    "∑",
    "sum",
    "operator",
    ["Summation over an indexed sequence."],
    ["\\sum"],
    "∑ᵢ₌₁ⁿ xᵢ",
  ),
  entry(
    "∏",
    "product",
    "operator",
    ["Multiplication over an indexed sequence."],
    ["\\prod"],
    "∏ᵢ₌₁ⁿ xᵢ",
  ),
  entry(
    "∫",
    "integral",
    "calculus",
    ["Accumulated quantity; area under a curve for a definite integral."],
    ["\\int"],
    "∫ₐᵇ f(x) dx",
  ),
  entry(
    "∮",
    "contour integral",
    "calculus",
    ["An integral over a closed path or loop."],
    ["\\oint"],
    "∮ E · dl",
  ),
  entry(
    "∂",
    "partial derivative",
    "calculus",
    ["Derivative with respect to one variable while holding others fixed."],
    ["\\partial"],
    "∂f/∂x",
  ),
  entry(
    "∇",
    "nabla / del",
    "calculus",
    ["Vector differential operator; gives gradient, divergence or curl."],
    ["\\nabla"],
    "∇f",
  ),
  entry(
    "d/dt",
    "derivative with respect to time",
    "calculus",
    ["The rate of change of a quantity as time t changes."],
    undefined,
    "v = dx/dt",
  ),
  entry(
    "′",
    "prime",
    "calculus",
    ["A derivative (f′), a new version of a variable, or arcminutes by context."],
    ["\\prime"],
    "f′(x)",
  ),
  entry(
    "→",
    "maps to / tends to",
    "relation",
    ["A mapping, direction, or limiting behavior."],
    ["\\to", "\\rightarrow"],
    "x → 0",
  ),
  entry(
    "⇒",
    "implies",
    "relation",
    ["The statement on the left logically entails the one on the right."],
    ["\\Rightarrow", "\\Longrightarrow"],
    "A ⇒ B",
  ),
  entry(
    "⇔",
    "if and only if",
    "relation",
    ["Each statement implies the other; logical equivalence."],
    ["\\Leftrightarrow"],
    "A ⇔ B",
  ),
  entry(
    "∀",
    "for all",
    "set-logic",
    ["Universal quantifier: a statement holds for every element."],
    ["\\forall"],
    "∀x ∈ ℝ",
  ),
  entry(
    "∃",
    "there exists",
    "set-logic",
    ["Existential quantifier: at least one element satisfies a statement."],
    ["\\exists"],
    "∃x: x² = 2",
  ),
  entry(
    "∈",
    "is an element of",
    "set-logic",
    ["The object belongs to a set."],
    ["\\in"],
    "π ∈ ℝ",
  ),
  entry(
    "∉",
    "is not an element of",
    "set-logic",
    ["The object does not belong to a set."],
    ["\\notin"],
    "π ∉ ℚ",
  ),
  entry(
    "⊂",
    "proper subset",
    "set-logic",
    ["Every element of the left set is in the right, and the sets differ."],
    ["\\subset"],
    "ℕ ⊂ ℤ",
  ),
  entry(
    "⊆",
    "subset or equal",
    "set-logic",
    ["Every element of the left set is also in the right set."],
    ["\\subseteq"],
    "A ⊆ B",
  ),
  entry(
    "∪",
    "union",
    "set-logic",
    ["The set of elements in either set."],
    ["\\cup"],
    "A ∪ B",
  ),
  entry(
    "∩",
    "intersection",
    "set-logic",
    ["The set of elements shared by both sets."],
    ["\\cap"],
    "A ∩ B",
  ),
  entry(
    "∅",
    "empty set",
    "set-logic",
    ["The set containing no elements."],
    ["\\emptyset"],
    "A ∩ B = ∅",
  ),
  entry(
    "ℕ",
    "natural numbers",
    "set-logic",
    ["The natural numbers; whether 0 is included depends on convention."],
    ["\\mathbb{N}"],
    "1 ∈ ℕ",
  ),
  entry(
    "ℤ",
    "integers",
    "set-logic",
    ["The positive and negative whole numbers and zero."],
    ["\\mathbb{Z}"],
    "−3 ∈ ℤ",
  ),
  entry(
    "ℚ",
    "rational numbers",
    "set-logic",
    ["Numbers expressible as a ratio of integers with nonzero denominator."],
    ["\\mathbb{Q}"],
    "1/2 ∈ ℚ",
  ),
  entry(
    "ℝ",
    "real numbers",
    "set-logic",
    ["All points on the continuous number line."],
    ["\\mathbb{R}"],
    "√2 ∈ ℝ",
  ),
  entry(
    "ℂ",
    "complex numbers",
    "set-logic",
    ["Numbers of the form a + bi with real a and b."],
    ["\\mathbb{C}"],
    "i ∈ ℂ",
  ),
  entry("¬", "not", "set-logic", ["Logical negation."], ["\\neg"], "¬A"),
  entry(
    "∧",
    "and",
    "set-logic",
    ["Logical conjunction; both statements must hold."],
    ["\\land"],
    "A ∧ B",
  ),
  entry(
    "∨",
    "or",
    "set-logic",
    ["Logical disjunction; at least one statement holds."],
    ["\\lor"],
    "A ∨ B",
  ),
  entry(
    "⊕",
    "direct sum / exclusive or",
    "set-logic",
    ["Direct sum, or exclusive-or in logic; addition modulo 2 in quantum gates."],
    ["\\oplus"],
    "a ⊕ b",
  ),
  entry(
    "⊗",
    "tensor product",
    "quantum-notation",
    ["Combines vector spaces or quantum systems."],
    ["\\otimes"],
    "|0⟩ ⊗ |1⟩",
  ),
  entry(
    "†",
    "dagger / Hermitian adjoint",
    "quantum-notation",
    ["Conjugate transpose of an operator or matrix."],
    ["\\dagger"],
    "A†",
  ),
  entry(
    "⟨",
    "left angle bracket",
    "quantum-notation",
    ["Starts a bra vector or an inner product."],
    ["\\langle"],
    "⟨ψ|",
  ),
  entry(
    "⟩",
    "right angle bracket",
    "quantum-notation",
    ["Ends a ket vector or an inner product."],
    ["\\rangle"],
    "|ψ⟩",
  ),
  entry(
    "|ψ⟩",
    "ket",
    "quantum-notation",
    ["A quantum state vector in Dirac notation."],
    ["\\ket"],
    "|ψ⟩",
  ),
  entry(
    "⟨ψ|",
    "bra",
    "quantum-notation",
    ["The dual vector of a ket; used to form inner products."],
    ["\\bra"],
    "⟨ψ|φ⟩",
  ),
  entry(
    "‖",
    "norm",
    "operator",
    ["The length or magnitude of a vector; context determines the norm."],
    ["\\|"],
    "‖v‖",
  ),
  entry(
    "|x|",
    "absolute value / magnitude",
    "operator",
    ["Distance from zero on the number line; for complex x, its modulus."],
    ["\\lvert", "\\rvert"],
    "|−3| = 3",
  ),
  entry(
    "!",
    "factorial",
    "operator",
    ["n! is the product of positive integers from 1 through n."],
    undefined,
    "5! = 120",
  ),
  entry(
    "°",
    "degree",
    "other",
    ["One 360th of a full turn, commonly used for angles and temperature."],
    ["\\degree"],
    "90°",
  ),
  entry("∠", "angle", "other", ["Denotes an angle in geometry."], ["\\angle"], "∠ABC"),
  entry(
    "⊥",
    "perpendicular",
    "other",
    ["Two lines or vectors meet at a right angle."],
    ["\\perp"],
    "a ⊥ b",
  ),
  entry(
    "∥",
    "parallel",
    "other",
    ["Lines do not meet, or a parallel-vector relation."],
    ["\\parallel"],
    "a ∥ b",
  ),
  entry(
    "∴",
    "therefore",
    "other",
    ["Introduces a conclusion."],
    ["\\therefore"],
    "a = b; ∴ b = a",
  ),
  entry("∵", "because", "other", ["Introduces a reason."], ["\\because"], "∵ a = b"),
  entry(
    "x̂",
    "x-hat",
    "other",
    ["A unit vector, an estimated value, or an operator depending on context."],
    ["\\hat"],
    "x̂",
  ),
  entry(
    "x̄",
    "x-bar",
    "other",
    ["The sample mean; in complex arithmetic, an overbar can mean complex conjugation."],
    ["\\bar"],
    "x̄ = (x₁ + … + xₙ)/n",
  ),
  entry(
    "ẋ",
    "x-dot",
    "calculus",
    ["A dot over x denotes its time derivative in Newtonian mechanics."],
    ["\\dot"],
    "ẋ = dx/dt",
  ),
  entry(
    "ẍ",
    "x-double-dot",
    "calculus",
    ["Two dots over x denote its second time derivative in Newtonian mechanics."],
    ["\\ddot"],
    "ẍ = d²x/dt²",
  ),
  entry(
    "*",
    "asterisk / convolution",
    "operator",
    [
      "A context-dependent marker; often convolution, an adjoint in some fields, or multiplication.",
    ],
    ["\\ast"],
    "f * g",
  ),
  entry(
    "ℏ",
    "h-bar",
    "constant",
    ["Reduced Planck constant h/(2π), about 1.054571817 × 10⁻³⁴ J·s."],
    ["\\hbar"],
    "E = ℏω",
  ),
  entry(
    "ħ",
    "h-bar (plain-text form)",
    "constant",
    ["Reduced Planck constant h/(2π); the curly-bar character is ℏ."],
    ["\\hbar"],
    "ħ = h/(2π)",
  ),
  entry(
    "ℓ",
    "ell",
    "other",
    ["Orbital angular-momentum quantum number or a length."],
    ["\\ell"],
    "ℓ = 0, 1, 2, …",
  ),
  entry(
    "e",
    "Euler's number / elementary charge",
    "constant",
    ["Euler's number in calculus, or the elementary charge in physics; context matters."],
    ["\\mathrm{e}"],
    "exp(x) = eˣ",
  ),
  entry(
    "i",
    "imaginary unit",
    "constant",
    ["The complex number with i² = −1; in physics it is often written j in engineering."],
    ["\\mathrm{i}"],
    "eⁱπ + 1 = 0",
  ),
  entry(
    "∘",
    "composition / degree sign",
    "operator",
    ["Function composition (f ∘ g); in other contexts, a circle or degree mark."],
    ["\\circ"],
    "(f ∘ g)(x)",
  ),
  entry(
    "mod",
    "modulo",
    "operator",
    ["Remainder arithmetic or congruence with respect to a modulus."],
    ["\\bmod"],
    "17 mod 5 = 2",
  ),
  entry(
    "gcd",
    "greatest common divisor",
    "operator",
    ["The largest positive integer dividing each of the given integers."],
    ["\\gcd"],
    "gcd(12, 18) = 6",
  ),
  entry(
    "Tr",
    "trace",
    "operator",
    ["Sum of the diagonal entries of a square matrix."],
    ["\\operatorname{Tr}"],
    "Tr(A)",
  ),
  entry(
    "ln",
    "natural logarithm",
    "operator",
    ["Logarithm to base e."],
    ["\\ln"],
    "ln(e) = 1",
  ),
  entry(
    "log",
    "logarithm",
    "operator",
    ["A logarithm; the base is written or determined by convention."],
    ["\\log"],
    "log₁₀(100) = 2",
  ),
  entry(
    "exp",
    "exponential",
    "operator",
    ["The exponential function, exp(x) = eˣ."],
    ["\\exp"],
    "exp(0) = 1",
  ),
  entry(
    "lim",
    "limit",
    "calculus",
    ["The value a function approaches as its input approaches a value."],
    ["\\lim"],
    "limₓ→₀ sin(x)/x = 1",
  ),
  entry(
    "sin",
    "sine",
    "operator",
    ["The trigonometric function giving the vertical coordinate on the unit circle."],
    ["\\sin"],
    "sin(π/2) = 1",
  ),
  entry(
    "cos",
    "cosine",
    "operator",
    ["The trigonometric function giving the horizontal coordinate on the unit circle."],
    ["\\cos"],
    "cos(0) = 1",
  ),
  entry(
    "max",
    "maximum",
    "operator",
    ["The greatest value in a set or range."],
    ["\\max"],
    "max(x, y)",
  ),
  entry(
    "⋯",
    "midline ellipsis",
    "other",
    ["Continuation of a sequence or a repeated series of centered terms."],
    ["\\cdots"],
    "1 + 2 + ⋯ + n",
  ),
  entry(
    "⇌",
    "reversible reaction / equilibrium",
    "relation",
    ["A reaction or process can proceed in either direction."],
    ["\\rightleftharpoons"],
    "A ⇌ B",
  ),
  entry(
    "ⁿ",
    "superscript n",
    "other",
    ["A raised index commonly marks a power or a tensor index."],
    undefined,
    "xⁿ",
  ),
  entry(
    "ₙ",
    "subscript n",
    "other",
    ["A lowered index commonly labels a sequence member or component."],
    undefined,
    "aₙ",
  ),
  entry(
    "𝒟",
    "script D",
    "quantum-notation",
    [
      "A functional integration measure; in a path integral, 𝒟x denotes integration over paths.",
    ],
    ["\\mathcal{D}"],
    "∫ 𝒟x",
  ),
  entry(
    "ϵ",
    "epsilon variant",
    "greek-lower",
    ["A common alternate handwritten or typeset form of lowercase epsilon."],
    ["\\epsilon"],
    "ϵ₀",
  ),
  entry(
    "ϑ",
    "theta variant",
    "greek-lower",
    ["An alternate form of lowercase theta, often used for a second angle."],
    ["\\vartheta"],
    "ϑ",
  ),
  entry(
    "ϕ",
    "phi variant",
    "greek-lower",
    ["An alternate form of lowercase phi."],
    ["\\varphi"],
    "ϕ",
  ),
  entry(
    "ς",
    "final sigma",
    "greek-lower",
    ["The word-final form of sigma; rarely used as a mathematical variable."],
    ["\\varsigma"],
    "ς",
  ),
  entry(
    "ϖ",
    "pi variant",
    "greek-lower",
    ["An alternate form of lowercase pi."],
    ["\\varpi"],
    "ϖ",
  ),
  entry(
    "ϱ",
    "rho variant",
    "greek-lower",
    ["An alternate form of lowercase rho."],
    ["\\varrho"],
    "ϱ",
  ),
  entry(
    "⁺",
    "superscript plus",
    "other",
    ["A raised plus sign, often indicating positive charge."],
    ["\\text{+}"],
    "Na⁺",
  ),
  entry(
    "⁻",
    "superscript minus",
    "other",
    ["A raised minus sign, often indicating negative charge or a negative exponent."],
    ["\\text{-}"],
    "10⁻³",
  ),
  entry(
    "²",
    "superscript two",
    "other",
    ["Square or second power."],
    ["\\text{2}"],
    "x²",
  ),
  entry("³", "superscript three", "other", ["Cube or third power."], ["\\text{3}"], "x³"),
  entry("⁴", "superscript four", "other", ["Fourth power."], ["\\text{4}"], "x⁴"),
  entry(
    "ᵘ",
    "superscript u",
    "other",
    ["A raised u used as an index or exponent."],
    undefined,
    "γᵘ",
  ),
  entry(
    "₀",
    "subscript zero",
    "other",
    ["A zero subscript often marks a reference or ground-state value."],
    undefined,
    "ε₀",
  ),
  entry(
    "₁",
    "subscript one",
    "other",
    ["A first component or indexed quantity."],
    undefined,
    "x₁",
  ),
  entry(
    "₂",
    "subscript two",
    "other",
    ["A second component or indexed quantity."],
    undefined,
    "x₂",
  ),
  entry(
    "₃",
    "subscript three",
    "other",
    ["A third component or indexed quantity."],
    undefined,
    "x₃",
  ),
  entry(
    "₄",
    "subscript four",
    "other",
    ["A fourth component or indexed quantity."],
    undefined,
    "x₄",
  ),
  entry(
    "↪",
    "injective map",
    "set-logic",
    ["An injective mapping or inclusion."],
    ["\\hookrightarrow"],
    "A ↪ B",
  ),
];
